### ISSUE TITLE
[question] Why do I get "No CSR-enabled webparts found on the page"?

### ISSUE THREAD

**Issue by egidiocs** [andrei-markeev/cisar#21]
awesome tool! I'm getting this error in default forms. MDS is off.
thank you in advance.
-egidio @egidiocs
![image](https://cloud.githubusercontent.com/assets/1933529/16789957/2f1e140e-4888-11e6-9367-0898c30ab735.png)

**Comment by joweiser** [comment]
Hey @egidiocs did you install from the Chrome Web Store or from the github repository?
I'm asking because this issue may already be solved. See over here: https://github.com/andrei-markeev/cisar/issues/20

**Comment by andrei-markeev** [comment]
Yep, this is already solved but not on Chrome Web Store. I'll be updating Chrome Web Store version shortly.

**Comment by andrei-markeev** [comment]
I pushed the latest changes to Chrome Web Store, including fix for this problem. Version should be 2.0.0 now. If it doesn't update, go to chrome://extensions, tick [x] Developer mode, and press [Update extensions now...] button.

**Comment by nyn3x** [comment]
I have a similar problem. I'm on a list-view (http://portal/sites/foo/_layouts/15/start.aspx#/Lists/samplelist/AllItems.aspx) and I get the "No CSR-enabled webparts found on the page" message - even though the version of CSR is 2.0

**Comment by andrei-markeev** [comment]
Hi, indeed something with list views. Thanks for reporting, I'm investigating it right now.

**Comment by andrei-markeev** [comment]
Ok I fixed this in commit https://github.com/andrei-markeev/cisar/commit/465953d83df281218a500595c24515a9afe912e6 and I pushed the changes to Chrome Web Store, version 2.0.1.

Automatic update usually takes some while, so go to chrome://extensions, tick [x] Developer mode, and press [Update extensions now...] button.

Please tell me if it works for you now? It should, based on my testing.

For those interested what is happening: so basically the story is that in O365 they changed things so that webpart ids on a page now begin with WPQ1 instead of WPQ2. I was starting from WPQ2 when collecting webparts information from the page, so after this change, things stopped working.
I fixed this in Cisar 2.0, BUT this broke things for old O365 tenants and on-prem SP2013, and also for Wiki pages where this WPQ1-change seemingly was not applied.

**Comment by nyn3x** [comment]
Just checked with SP2013-OnPrem: seems to work :) Thx for the quick fix!!!! awesome!

**Comment by andrei-markeev** [comment]
Glad to hear that! :)
